apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentgpt-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agentgpt-db
  template:
    metadata:
      labels:
        app: agentgpt-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: agentgpt-secrets
              key: REWORKD_PLATFORM_DATABASE_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: agentgpt-config
              key: REWORKD_PLATFORM_DATABASE_NAME
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: agentgpt-config
              key: REWORKD_PLATFORM_DATABASE_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: agentgpt-secrets
              key: REWORKD_PLATFORM_DATABASE_PASSWORD
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: agentgpt-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: agentgpt-db
spec:
  selector:
    app: agentgpt-db
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP 