apiVersion: v1
kind: PersistentVolume
metadata:
  name: agentgpt-db-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/agentgpt-db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agentgpt-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi 